services:
  frontend:
    build: .
    container_name: velzia_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
